config/routes.rb
Rails.application.routes.draw do
  root "units#index"

  resources :units do
    resources :rates
  end

  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/rate.rb
class Rate < ApplicationRecord
belongs_to :unit
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_one :rate, dependent: :destroy
  accepts_nested_attributes_for :rate, allow_destroy: true

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: ->(email) {email.strip.downcase}

  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end
  generates_token_for :email_confirmation, expires_in: 24.hours do
    email
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  #  before_action: *add action to ensure that user is not signed in* 
  before_action :set_user_by_token, only: [:edit, :update]

  def new
  end

  def create
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset)
      ).password_reset.deliver_later
    end

    redirect_to root_path, notice: "Check you email to reset your password."
  end

  def edit
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: "Your password has been reset successfully. Please login"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    redirect_to new_password_reset_path alert: "Invalid token, please retry." unless @user.present?
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Your password has been updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(
      :password,
      :password_confirmation,
      :password_challenge
    ).with_defaults(password_challenge: "")
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_unit
  def create
    @rate = @unit.build_rate(rate_params)

    if @rate.save
      redirect_to unit_path(@unit), notice: "Rate was sucessfully created."
    else
      render "new", status: :unprocessable_entity
    end
  end
  def update
    @rate = @unit.rate
    if @rate.update(rate_params)
      redirect_to unit_path(@unit), notice: "Rate was successfully updated."
    else
      render "edit", status: :unprocessable_entity
    end
  end

  private

  def set_unit
    @unit = Unit.find(params[:unit_id])
  end

  def rate_params
    params.require(:rate).permit(:dayrate, :weekrate, :monthrate)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  
  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user
      redirect_to root_path, notice: "You have been signed in successfully."
    else
      flash[:alert] = "Invalid email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
    @rate = @unit.rate
  end

  def new
    @unit = Unit.new
    @unit.build_rate
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      redirect_to @unit
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update(unit_params)
      redirect_to @unit
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to units_path, status: :see_other
  end

  private
    def unit_params
      params.require(:unit).permit(:name, :description, rate_attributes: [:id, :dayrate, :weekrate, :monthrate, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rentcard" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>

    <% if user_signed_in? %>
      <%= link_to "Edit Password", edit_password_path %>
      <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_registration_path %>
      <%= link_to "Log In", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  <% end %>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit "Reset Your Password" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Your Password</h1>


<%= form_with model: @user, url: password_reset_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit "Reset password" %>
  </div>
<% end %>

app/views/rates/_form.html.erb
<%= form_with model: [ @unit, @unit.rate || @unit.build_rate ] do |form| %>
  <p>
    <%= form.label :dayrate %><br>
    <%= form.text_field :dayrate %>
  </p>
  <p>
    <%= form.label :weekrate %><br>
    <%= form.text_area :weekrate %>
  </p>
   <p>
    <%= form.label :monthrate %><br>
    <%= form.text_area :monthrate %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/rates/_rate.html.erb
  <p>
    <strong>Daily rental rates:</strong>
    <%= @unit.rate.dayrate %>
  </p>

  <p>
    <strong>Weekly rental rates:</strong>
    <%= @unit.rate.weekrate %>
  </p>

  <p>
    <strong>Monthly rental rates:</strong>
    <%= @unit.rate.monthrate %>
  </p>

app/views/units/_form.html.erb
<%= form_with model: unit do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% unit.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% unit.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Edit Unit</h1>

<%= render "form", unit: @unit %>

app/views/units/index.html.erb
<h1>Equipment List</h1>

<ul>
  <% @units.each do |unit| %>
    <li>
      <%= link_to unit.name, unit %>
    </li>
  <% end %>
</ul>

<%= link_to "New Unit", new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render "form", unit: @unit %>

app/views/units/show.html.erb
<h1><%= @unit.name %></h1>

<p><%= @unit.description %>

<ul>
    <li><%= link_to "Edit", edit_unit_path(@unit) %></li>
    <li><%= link_to "Destroy", unit_path(@unit), data: {
            turbo_method: :delete,
            turbo_confirm: :"Are you sure?"
        } %></li>
</ul>

<% if @unit.rate.present? %>
  <h2>Rental rate:</h2>
  <%= render @unit.rate %>
<% else %>
  <p>Call for rates for this unit.</p>
<% end %>

<h2>Add or update rate:</h2>
<%= render "rates/form", unit: @unit %>